In [1]:
import numpy as np

In [5]:
a = np.random.randn(3,4)
a

array([[-0.17711847,  0.83494706,  1.59514694,  0.8125408 ],
       [ 1.20594751,  0.19507098, -0.96309942,  0.12427439],
       [-1.1159942 ,  0.67767695,  0.8236862 ,  0.12230287]])

In [7]:
b = a[:]
b

array([[-0.17711847,  0.83494706,  1.59514694,  0.8125408 ],
       [ 1.20594751,  0.19507098, -0.96309942,  0.12427439],
       [-1.1159942 ,  0.67767695,  0.8236862 ,  0.12230287]])

In [11]:
b

array([[-0.17711847,  0.83494706,  1.59514694,  0.8125408 ],
       [ 1.20594751,  0.19507098, -0.96309942,  0.12427439],
       [-1.1159942 ,  0.67767695,  0.8236862 ,  0.12230287]])

In [13]:
b.sum(axis=1, keepdims=True)

array([[3.06551634],
       [0.56219346],
       [0.50767182]])

In [25]:
mean, std = b.mean(axis=1, keepdims=True), b.std(axis=1, keepdims=True)
mean,std

(array([[0.76637908],
        [0.14054837],
        [0.12691795]]),
 array([[0.62926073],
        [0.76752057],
        [0.76381827]]))

In [26]:
c = (b-mean)/std
c

array([[-1.4993746 ,  0.10896593,  1.31705002,  0.07335865],
       [ 1.38810499,  0.07103734, -1.43793903, -0.02120331],
       [-1.62723544,  0.72106025,  0.91221731, -0.00604212]])

In [27]:
c.mean(axis=1), c.std(axis=1)

(array([-1.07552856e-16,  7.02563008e-17, -2.68882139e-17]),
 array([1., 1., 1.]))

In [29]:
np.zeros_like(c)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
c.diagonal()

array([-1.4993746 ,  0.07103734,  0.91221731])

In [34]:
c[np.arange(3), np.arange(2,-1, -1)]

array([ 1.31705002,  0.07103734, -1.62723544])

In [35]:
c.dot(c.T)

array([[ 4.        , -3.96894178,  3.71939907],
       [-3.96894178,  4.        , -3.5191362 ],
       [ 3.71939907, -3.5191362 ,  4.        ]])

In [36]:
c.T.dot(c)

array([[ 6.82285484e+00, -1.23810826e+00, -5.45515402e+00,
        -1.29592562e-01],
       [-1.23810826e+00,  5.36847767e-01,  6.99129861e-01,
         2.13063409e-03],
       [-5.45515402e+00,  6.99129861e-01,  4.63442981e+00,
         1.21594349e-01],
       [-1.29592562e-01,  2.13063409e-03,  1.21594349e-01,
         5.86757905e-03]])

In [37]:
np.where(c>0, 1, 0)

array([[0, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 0]])

In [38]:
np.empty_like(c)

array([[-1.4993746 ,  0.10896593,  1.31705002,  0.07335865],
       [ 1.38810499,  0.07103734, -1.43793903, -0.02120331],
       [-1.62723544,  0.72106025,  0.91221731, -0.00604212]])

In [40]:
d = np.empty((2,3))
d[1,1]

np.float64(0.0)

In [42]:
import math
0.2/(0.2+0.8*math.pow(0.6,3))

0.5364806866952789

In [3]:
arr = np.array([[0,1,0,0], [1, 0, 0, 0], [1,1,1,1]])

In [4]:
arr

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 1]])

In [7]:
np.argmax(arr, axis=0)

array([1, 0, 2, 2])

In [11]:
np.random.permutation(arr.shape[0])

array([1, 0, 2])